### ISSUE TITLE
problem with non-core probes

### ISSUE THREAD

**Issue by MigueLugo** [prody/DruGUI#1]
Hi there

When I use the druggi command with another probes  the job halts when solvating the system, like this
......
Command: solvate larvinapo_autopsf.psf larvinapo_autopsf.pdb -o apo6/intermediate -b 2.4 -x 11 -y 11 -z 11 +x 11 +y 11 +z 11 -spdb C:/Program Files (x86)/University of Illinois/VMD/plugins/noarch/tcl/drugui/probe.pdb -spsf C:/Program Files (x86)/University of Illinois/VMD/plugins/noarch/tcl/drugui/probe.psf -stop C:/Program Files (x86)/University of Illinois/VMD/plugins/noarch/tcl/drugui/probe2.top -ks "name OH2" -ws 62.3572 -rotate -rotinc 10 -rotsel {all}
Info) Usage: solvate ...
Info) Usage: solvate ... to just create a water box
.....
And that also happen even when I select the option -solvent yes (for default probes). However, using the GUI it works well for the core probes.

So, How can I make the command works for non-core probes?? Thanks in advanced

**Comment by jamesmkrieger** [comment]
Please see http://prody.csb.pitt.edu/tutorials/drugui_tutorial/cgenff.html and let us know if it still doesn’t work
